public with sharing class FormatDemo {
    private String name;
private Integer num;                 public Boolean b;

    public FormatDemo(Integer num) {
    this.num=num;
}

public static void doSomthing(String s){ System.debug('i did something: '+s);}

        public static void doSomethingElse(Boolean b) {
            if(b==false)System.debug('false');
            
            
            
            for(Integer i=0;i<4;i++){
                System.debug('hi');
        Integer twoTimes = i*2;System.debug('Two times ' + twoTimes);



            }
        }



public static void thisMethodIsSeriouslyAllOnOneLine(SObject obj){System.debug('hi');System.debug('hi');System.debug('hi');switch on obj {when Account a{}when else {}}}}
